spring.application.name=agent-elaira-gpt-server
server.port=${SERVER_PORT:7003}

app.security.token=
app.openai.api-key=1
app.openai.model=${APP_OPENAI_MODEL:gpt-5.4-nano}
app.openai.transcription-model=${APP_OPENAI_TRANSCRIPTION_MODEL:whisper-1}
app.openai.base-url=${APP_OPENAI_BASE_URL:https://api.openai.com}
app.openai.mock-enabled=${APP_OPENAI_MOCK_ENABLED:false}
app.audio.max-file-size-mb=${APP_AUDIO_MAX_FILE_SIZE_MB:25}
app.logging.debug-packets=${APP_LOGGING_DEBUG_PACKETS:false}

app.telegram.bot-token=8614414510:AAF-mTZS8JKyp2gZIS4t0n0pE4eXsNdrt1w
app.telegram.chat-id=6919816967

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:./data/app.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

logging.file.name=${LOG_FILE_NAME:./logs/agent-elaira-gpt-server.log}
logging.level.com.example.dialogueapi.client=${LOG_LEVEL_CLIENT:INFO}
